// pages/Works/index.vue
<style src="~/style/pages/worksIndex.scss" lang="scss" scoped></style>

<template lang="pug">
  div.works-page
    h3 Works
    div.contents
        Card(v-for="proj in projects" v-bind:project="proj" v-bind:key="proj.id")
    p
        nuxt-link(to="/") Top Page
</template>

<script>
import Card from '~/components/Card.vue';
import { sourceFileArray } from '~/contents/summary.json';
import Debug from 'debug';

const debug = Debug('works:index');

export default {
    components: {
        Card
    },
    head() {
        return {
            title: 'Works',
            meta: [
                {
                    property: 'og:title',
                    content: 'Kazuma Takada\'s Portfolio | Works'
                },
                {
                    property: 'og:type',
                    content: 'article'
                },
                {
                    property: 'og:url',
                    content: 'http://tkd.work/Works'
                },
                {
                    property: 'og:site_name',
                    content: 'Kazuma Takada\'s Portfolio | Works'
                },
                {
                    property: 'og:description',
                    content: 'Please visit my portfolio !'
                },
                {
                    name: 'twitter:card',
                    content: 'summary_large_image'
                },
                {
                    name: 'twitter:site',
                    content: '@fmsuvM'
                },
                {
                    name: 'twitter:creator',
                    content: '@fmsuvM'
                },
                {
                    name: 'twitter:domain',
                    content: 'tkd.work/Works'
                },
                {
                    name: 'twitter:title',
                    content: 'Kazuma Takada Portfolio | Works'
                },
                {
                    name: 'twitter:description',
                    content: 'Please visit my portfolio !'
                },
                {
                    name: 'twitter:image',
                    content:
                        'https://i.gyazo.com/123efba36bfa12ae7f415b59c2dae32a.png'
                }
            ]
        };
    },
    data() {
        const _projects = sourceFileArray.filter(element => {
            return element.match(/projects/);
        });
        const _contents = _projects.map(element => {
            const refactorEl = element.split('.')[0];
            return refactorEl.split('/')[2];
        });
        const contents = _contents.map(element => {
            const params = {};
            return Object.assign(
                {},
                require(`~/contents/dist/projects/${element}.json`),
                params
            );
        });
        const sortedContents = contents.sort((a, b) => {
            return a.date < b.date ? 1 : -1;
        });
        return {
            projects: sortedContents
        };
    }
};
</script>

// src/javascripts/pages/Works.jsx
import React, { Component } from 'react';
import Debug from 'debug';
import { Helmet } from 'react-helmet';
import MediaQuery from 'react-responsive';

import ProjectCard from '../components/ProjectCard';

const debug = Debug('Works:jsx:');

export default class Works extends Component {
    constructor(props) {
        super(props);
    }

    render() {
        // debug(fabnavi);
        return (
            <div>
                <Helmet>
                        <title>Kazuma Takada Works</title>
                        <meta property="og:title" content="Kazuma Takada Portfolio | Works" />
                        <meta property="og:type" content="article" />
                        <meta property="og:url" content="http://fmsuvm.github.io/#/works" />
                        <meta property="og:site_name" content="Kazuma Takada Portfolio" />
                        <meta property="og:description" content="Please visit my portfolio !" />
                        <meta name="twitter:card" content="summary_large_image" />
                        <meta name="twitter:site" content="@fmsuvM" />
                        <meta name="twitter:creator" content="@fmsuvM" />
                        <meta name="twitter:domain" content="fmsuvM.github.io" />
                        <meta name="twitter:title" content="Kazuma Takada Profile" />
                        <meta name="twitter:description" content="Please visit my portfolio !" />
                        <meta name="twitter:image" content="https://i.gyazo.com/123efba36bfa12ae7f415b59c2dae32a.png" />
                </Helmet>
                <MediaQuery maxWidth={1049}>
                    <div className="work-list-middle">
                        <ProjectCard className="project-card" projectName="fabnavi" />
                        <ProjectCard className="project-card" projectName="shogg" />
                        <ProjectCard className="project-card" projectName="bookroof" />
                        <ProjectCard className="project-card" projectName="unpresence" />
                        <ProjectCard className="project-card" projectName="ghostcreator" />
                        <ProjectCard className="project-card" projectName="throughstudio" />
                        <ProjectCard className="project-card" projectName="flexibleinterface" />
                        <ProjectCard className="project-card" projectName="fabnavihakodate" />
                        <ProjectCard className="project-card" projectName="todopop" />
                        <ProjectCard className="project-card" projectName="hishatsuuti" />
                        <ProjectCard className="project-card" projectName="icc" />
                        <ProjectCard className="project-card" projectName="shoukaiocreilly" />
                        <ProjectCard className="project-card" projectName="fabdesk" />
                        <ProjectCard className="project-card" projectName="fabspace" />
                        <ProjectCard className="project-card" projectName="jitsuyouocreilly" />
                        <ProjectCard className="project-card" projectName="sharetterhci" />
                        <ProjectCard className="project-card" projectName="jissenocreilly" />
                    </div>
                </MediaQuery>
                <MediaQuery minWidth={1050}>
                    <div className="work-list">
                        <ProjectCard className="project-card" projectName="fabnavi" />
                        <ProjectCard className="project-card" projectName="shogg" />
                        <ProjectCard className="project-card" projectName="bookroof" />
                        <ProjectCard className="project-card" projectName="unpresence" />
                        <ProjectCard className="project-card" projectName="ghostcreator" />
                        <ProjectCard className="project-card" projectName="throughstudio" />
                        <ProjectCard className="project-card" projectName="flexibleinterface" />
                        <ProjectCard className="project-card" projectName="fabnavihakodate" />
                        <ProjectCard className="project-card" projectName="todopop" />
                        <ProjectCard className="project-card" projectName="hishatsuuti" />
                        <ProjectCard className="project-card" projectName="icc" />
                        <ProjectCard className="project-card" projectName="shoukaiocreilly" />
                        <ProjectCard className="project-card" projectName="fabdesk" />
                        <ProjectCard className="project-card" projectName="fabspace" />
                        <ProjectCard className="project-card" projectName="jitsuyouocreilly" />
                        <ProjectCard className="project-card" projectName="sharetterhci" />
                        <ProjectCard className="project-card" projectName="jissenocreilly" />
                    </div>
                </MediaQuery>
            </div>
        )
    }
}
